#mysql\u76F8\u5173
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taotao?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#mybatis\u76F8\u5173
mybatis:
  type-aliases-package: com.longe.entity
  mapper-locations: mapper/*.xml

